### PR TITLE
Fix: Update and install in the appropriate sections

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates composer itself in the `before_install` section
* [x] installs dependencies with composer in the `install` section

### CODE REVIEW

**Comment by reinink** [comment]
This looks good to me, but there are some conflicts. Can I bug you once again to fix? :speak_no_evil:

**Comment by localheinz** [comment]
@reinink 

:+1:

**Comment by localheinz** [comment]
@reinink 

Blocked by #103.

**Comment by reinink** [comment]
We're making progress!

**Comment by localheinz** [comment]
:clap:

**Pull request merged**
