### PR TITLE
WIP: Initial Auto Escape Implementation #200

### PR DESCRIPTION
**Pull request by ragboyjr**
- Need to add integration tests
- Moved escape to a utility and service to be used throughout
  extensions

Signed-off-by: RJ Garcia <rj@bighead.net>

### CODE REVIEW

**Comment by ragboyjr** [comment]
After some tinkering, i think this AutoEscape extension is going to work. There are a few limitations which I'll address, but for the most part it just works.

1. Performance Overhead. There will be a tiny performance overhead because whenever a var is accessed it has to create a new lightweight proxy object.
2. Strict comparisons and type checks will not work. Since each variable is a different instance of the EscapedProxy, strict comparisons on objects will fail, same reasoning is applied to type checks. You can access the wrapped instance by calling `$var->__unwrap()` to get access to the underlying var if you need such comparisons.
3. You'll need to provide an exclude list for any types that you definitely don't want escaped. For example, in that list would be the RenderContext, that variable should not provide automatic escaping since it produces unescaped html.
4. Debugging might be a bit harder if you print an object from the template since they'll be instances of EscapedProxy. But like I said, you can always just unwrap the value if you need to.

**Comment by ragboyjr** [comment]
@reinink This is something you and I have talked about before, and I was curious on what you thought or any other drawbacks besides what i've listed?

Since it's an extension, it is optional, and can be disabled or enabled per project.

**Comment by reinink** [comment]
Hey there @ragboyjr! So, yeah, I've been down this road before...

https://github.com/thephpleague/plates/issues/21
https://github.com/thephpleague/plates/issues/23
https://github.com/thephpleague/plates/issues/24

My recommendation? Don't try to do auto-escaping in plain PHP. It's extremely complicated, there are lots of gotchas, and it won't be very performant. Honestly, if you want auto-escaping, it probably makes sense to use a library like Twig or Blade.

I say this after having invested a lot of energy into trying to solve this very problem.

**Comment by ragboyjr** [comment]
Yes totally understand. I personally wouldn't have much need or use for something like this because it's pretty simple to just call escape on my variables, and I usually always know when I need to escape data. 

And after reading through, yes, even if I'm able to fix the specific issues you had, there likely will be some esoteric use case that will cause this to break since this is just a hack. And I definitely don't want to support a feature like this that I don't use in my own projects. Thanks very much for those references @reinink.

However, because it's just an extension, it can be completely opt-in. I'll leave this PR open for a bit, and depending on the response I get from users, I can do the following:

1. Include this extension in plates, but force it to be opt-in
2. Create in my own personal repo for this extension and have it documented otherwise (anybody else could also go about doing this as well)
3. Let this die, and someone else could figure something out.

**Comment by lkraav** [comment]
Interesting comment from @reinink.

So what are we thinking here, is this going to die?

WordPress Coding Standards combined w/ PHPCS are able to flag all non-escaped output, so I wouldn't need it very much, for one.

But wondering if there's any general interest out there.

**Comment by ragboyjr** [comment]
@lkraav there doesn't seem to be a huge community desire for this feature, so not sure if it's quite worth the effort of maintaining at this point.

**Comment by ragboyjr** [comment]
We won't be implementing auto-escaping, or at least not like that, there could be a community plugin if someone felt it was really necessary, but I think a lint rule would be a much better approach to this.

**Pull request closed without merging**
