### PR TITLE
Retrieve Engine from the Template

### PR DESCRIPTION
**Pull request by funivan**
Add ability to return current engine from the Template

### CODE REVIEW

**Comment by ragboyjr** [comment]
@funivan thanks the PR. What use case do you have for allowing the engine to be accessible?

**Comment by reinink** [comment]
I'm curious about that too, since the `$engine` is a property on `Template` already.

**Comment by funivan** [comment]
I use `AdvertWidget` to display advert in the site and in the letter template.
There are 2 engines in the container: `LetterTemplateEngine` and `SiteTemplateEngine`
They are configured in different manner.

```php
    class AdvertWidget {
      public function render(Engine $engine) {
        $engine->render('adsWidget', ['advert' => $this->advert]);
      }
    }
```

 So when i want to use `AdvertWidget` in the site layout a do the following things:
```html
/** @var Engine $this */
<div class="sidebar">
  <div class="advert">
   <?= $advertWidget->render($this->getEngine())?>
  </div>
</div>
```

Here is the code how I use `AdvertWidget` in the letter:

```html
/** @var Engine $this */
<div class="advert-row">
  <?= $advertWidget->render($this->getEngine())?>
</div>
```
I can use `fetch` method:
```html
/** @var Engine $this */
<div class="advert-row">
  <?= $this->fetch('advertWidget', ['advertWidget'=>$advertWidget)?>
</div>
```
But then I should repeat viewId and all parameters every time.

**Comment by reinink** [comment]
Have you tried just doing this?

```php
<?= $advertWidget->render($this->engine)?>
```

**Comment by funivan** [comment]
@reinink yes. This solutions works fine. But IDE (PhpStorm) does not complete me engine property.

**Comment by funivan** [comment]
ping.

**Comment by ragboyjr** [comment]
@funivan I'm thinking of closing this since it doesn't feel consistent with the other methods in the template class. We don't have any other getters to access the protected data in the template, and you can already access it via the property.

**Pull request closed without merging**
