### PR TITLE
Adding Community Extension

### PR DESCRIPTION
**Pull request by basteyy**
Add [Plates Local Assets Copy Extension](https://github.com/basteyy/plates-local-assets-copy)

### CODE REVIEW

**Comment by kros** [comment]
I've developed a simple extension to set/push/unshift sections content into templates from the controller.
I think it could be useful for other users and I'd like to share it:
[Sections content set/push/unshift from controller](https://github.com/kros/PlatesSectionsInsertion)

**Comment by ragboyjr** [comment]
@basteyy not sure how I missed this, mind rebasing off of v3 and seeing if we can get the checks to pass?

**Comment by ragboyjr** [comment]
@kros you should submit a separate PR to have your extension listed.

**Comment by basteyy** [comment]
> @basteyy not sure how I missed this, mind rebasing off of v3 and seeing if we can get the checks to pass?

Yep

**Pull request merged**
