### PR TITLE
Return data for use in extensions

### PR DESCRIPTION
**Pull request by chrismichaels84**
In response to #60 this pull request gives access to template data for extensions. In effect, calling `$template->data()` with no arguments will return the data array. I added a test for this. I am doing another pull request for documentation.

Now you can do what was described to badpenguin. I've check this. It works wonderfully.

``` php
<?php

use League\Plates\Engine;
use League\Plates\Extension\ExtensionInterface;

class MyExtension implements ExtensionInterface
{
    public $template;

    public function register(Engine $engine)
    {
        $engine->registerFunction('default', [$this, 'extension_default']);
    }

    function extension_default($var, $def = '')
    {
        $data = $this->template->data();

        if (isset($data[$var])) {
            return $data[$var];
        }

        return $def;
    }
}
```

And in the template

``` php
<html lang="<?=$this->default('page_lang', 'en')?>">
```

If you've already implemented this, or if you wanted to do it a different way, no biggie. Just though I'd pitch it.

### CODE REVIEW

**Comment by reinink** [comment]
Hey @chrismichaels84, thanks for all the work you've put into this library the last few days! I'm having a REALLY busy week, and while I want to dig through all your pull requests right now, I probably won't have a chance until next week. Please be patient with me. :)

**Comment by chrismichaels84** [comment]
Take your time man. I'm just wantin' to help out.

**Comment by eko3alpha** [comment]
I was looking for a solution to this very issue and noticed in your example you're missing a closing ( ' ) after page_lang

    <html lang="<?=$this->default('page_lang, 'en')?>">

should be

    <html lang="<?=$this->default('page_lang', 'en')?>">

**Comment by chrismichaels84** [comment]
ah...quotes and semicolons. The bane of my existence. Thanks for the catch.

Any word on these Pull Requests?

**Comment by reinink** [comment]
@chrismichaels84 Soon. Very sorry for the delay. See [this](https://twitter.com/reinink/status/590132420558639104) and maybe [this](https://twitter.com/reinink/status/590132439986610176).

**Comment by chrismichaels84** [comment]
Lol, I hear you man. No problem. I'm running what I need off my fork
anyway. Good luck.

**Comment by ragboyjr** [comment]
👍

**Comment by ragboyjr** [comment]
@chrismichaels84 Are you around to support this PR? It looks like your original plates repo is gone.

**Pull request merged**
