### PR TITLE
allow multiple default directories

### LINKED ISSUE #59: addFolder is not what i want: how do i allow searching in more then 1 default directory?
I've an array of 4 directories, is it possible to have them as default search paths instead of just 1 ?

### PR DESCRIPTION
**Pull request by badpenguin**
Allow the default directory to be a string or an array, allowing multiple default directories to be used.
Internally its always stored as array.
This way is backward compatible.
Closes #59

### CODE REVIEW

**Comment by reinink** [comment]
Hey! Not ignoring this, but I've been away on a business trip all way, and this isn't an easy merge. There are many code formatting issues, and the builds are not passing. I'll have a closer look as soon as I have some time to spend on this.

**Comment by badpenguin** [comment]
uhm... sorry i think i was messing with netbeans and eclipse... will revert back to vim :)

**Comment by badpenguin** [comment]
test/build fails because tests about setDirectory/getDirectory must be rewritten, its an array now not a string

**Comment by badpenguin** [comment]
I don't use Plates anymore.

**Pull request closed without merging**
