### PR TITLE
Fixed invalid urls

### PR DESCRIPTION
**Pull request by iGusev**

### CODE REVIEW

**Comment by ragboyjr** [comment]
@iGusev are you still around? Let's change these urls to schemeless instead of https.

**Comment by ragboyjr** [comment]
@odahcam  if you have time, do you want to tackle this one?

**Comment by odahcam** [comment]
I can't edit here.

**Comment by ragboyjr** [comment]
This was fixed by #163 

Thanks @iGusev for bringing this up, and thanks @odahcam for making the update.

**Pull request closed without merging**
