### PR TITLE
Added extra check in URI extension. Solves thephpleague/plates#131

### PR DESCRIPTION
**Pull request by magnus-eriksson**
Added check to make sure array keys exist before trying to use them.

### CODE REVIEW

**Comment by ragboyjr** [comment]
@magnus-eriksson Can you add a test for this as well?

**Comment by magnus-eriksson** [comment]
@ragboyjr Sure. I'll sort it out.

**Comment by ragboyjr** [comment]
👍 Looks great man. I'll test it later on

**Comment by reinink** [comment]
Thanks @magnus-eriksson!

**Pull request merged**
