### PR TITLE
Exclude docs and example

### PR DESCRIPTION
**Pull request by vinkla**
Exclude the non-essentials docs and example from production.

### CODE REVIEW

**Comment by ExplicitDev** [comment]
I believe some of those docs are used to update the official website.
For example the next pull request #189 intends to update the [Community Extensions](http://platesphp.com/extensions/community/) page...

**Comment by vinkla** [comment]
> I believe some of those docs are used to update the official website.

This shouldn't prevent that? Right? This will prevent unnecessary files to be installed in production.

https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production

**Comment by ragboyjr** [comment]
I think this should be ok for merging in, if it jacks up the prod site we'll find out :).

**Comment by ragboyjr** [comment]
Thanks @vinkla for the contribution!

**Pull request merged**
