### PR TITLE
Make default template methods public.

### PR DESCRIPTION
**Pull request by reinink**
This makes these methods available to extensions.

### CODE REVIEW

**Comment by harikt** [comment]
Any reason the PR is waiting ?

**Comment by jails** [comment]
Looking forward this PR to be merged !

**Comment by jails** [comment]
Awesome thank you for the merge @reinink :+1: !
Ans a version bump would be greatly welcome ;-)

**Comment by reinink** [comment]
@jails You bet, it's coming! :)

**Pull request merged**
